'done'
hellhellpnick/Vodoriz_Alexander_AltexsoftLab pull request #2
Opened 2021-05-30 11:40 UTC by hellhellpnick

2021-05-30 11:42 UTC, Maxim-Bondar commented on .gitignore
> +node_modules/
this file should be in `main` branch

2021-05-30 11:44 UTC, Maxim-Bondar commented on src/css/core/_common.scss
> +}
add empty line between brackets and next selector, it's more readable

2021-05-30 11:45 UTC, Maxim-Bondar commented on src/css/core/_common.scss
> +input {
if you declare font-family for `body` , all elements will inherit this style

2021-05-30 12:05 UTC, Maxim-Bondar commented on src/css/core/_vars.scss
> +@function calcRem($size) {
this solution generate not the same sizes as was mentioned in design

2021-05-30 12:11 UTC, Maxim-Bondar commented on src/css/core/_mixins.scss
> +@mixin padding-hack($padding: 50%, $size: contain, $dev: false) {
you mentioned argument `padding` but use it only for padding-bottom it is confusing, also arg `$dev` not obvioswe what for it was created
This mixin is to common, you change a lot of styles for several elements, but mixin call `padding-hack`

2021-05-30 12:13 UTC, Maxim-Bondar commented on src/css/core/_mixins.scss
> +@mixin size($size) {
this mixin needs only for square generating, please call its appropriate

2021-05-30 12:20 UTC, Maxim-Bondar commented on src/css/core/_vars.scss
> +$white: white;
bad idea make variables with strict dependency to the value, imagene situation when you will change the value to another collor but the variable will have the `white` name, Was discussed on the last meeting

2021-05-30 12:21 UTC, Maxim-Bondar commented on src/css/core/_vars.scss
> +$max-width: 1440px;
the `$max-width` name is too general, max-width of what? where can I use this variable? It woulld be better to call this variable for example `container-width` etc.

2021-05-30 12:22 UTC, Maxim-Bondar commented on src/css/core/_vars.scss
> +$H400: calcRem(110px);
What those variable for?

2021-05-30 12:26 UTC, Maxim-Bondar commented on src/css/core/_vars.scss
> +$screen-iphone-plus: 414px;
`$screen-iphone` and `$screen-iphone-plus` are redundant . Yo even don't use such variables

2021-05-30 12:29 UTC, Maxim-Bondar commented on src/css/modules/_box.scss
> +  &-logo {
Please don't use this approach, it is a nice feature but from the practical side , it is difficult to find such selector in global search if you don't know that this class was written in such way

2021-05-30 12:31 UTC, Maxim-Bondar commented on src/css/modules/_box.scss
> +      flex-direction: row;
you have a mixin for flex, why you don't use it here?

2021-05-30 12:38 UTC, Maxim-Bondar commented on src/css/modules/_burger.scss
> +  &-line:not(:last-child) {
this selector is too expensive, you can change it to `.burger-line + .burger-line { margin-top: 8px }`

2021-05-30 12:39 UTC, Maxim-Bondar commented on src/css/modules/_box.scss
> +    background-color: #f2f2f2;
if you use variable, this color is also need to get from variable

2021-05-30 12:44 UTC, Maxim-Bondar commented on src/css/theme/_footer.scss
> +  &-title {
`-title` and `-subtitle` has a lot of common styles, you can create a common class and create a separete class for title where yu\ou just change a font size

2021-05-30 12:46 UTC, Maxim-Bondar commented on src/css/theme/_footer.scss
> +  &-logo {
the same as for comment for title

2021-05-30 12:47 UTC, Maxim-Bondar commented on src/css/theme/_nav-choose.scss
> +    height: 40px;
dont hardcode the values

2021-05-30 12:48 UTC, Maxim-Bondar commented on src/css/theme/_nav-choose.scss
> +      font-weight: 300;
this style is dublicated here

2021-05-30 12:49 UTC, Maxim-Bondar commented on src/css/theme/_nav-choose.scss
> +  border: 1.5px solid $green;
don't use a float values

2021-05-30 12:51 UTC, Maxim-Bondar commented on src/css/theme/_nav-choose.scss
> +    align-items: flex-start;
dublicated style from mixin above

2021-05-30 12:53 UTC, Maxim-Bondar commented on src/css/theme/_nav-list.scss
> +      @include flex(space-between, center, row);
I guess you don't need use a mixin here, because you need only override flex-direction, and there is no needed to dublicate other styles

2021-05-30 12:54 UTC, Maxim-Bondar commented on src/css/theme/_nav-list.scss
> +    content: "";
`content` must be in the first place

2021-05-30 12:55 UTC, Maxim-Bondar commented on src/css/theme/_nav-list.scss
> +  &-btn_small {
`btn-small` and `btn-large` has a lot of common styles , create a commn class for buttons and don't repeat yourself

2021-05-30 12:59 UTC, Maxim-Bondar commented on src/css/theme/_nav-list.scss
> +    list-style: none;
you can put this style in common styles for list elements because you don't need dots in whole page

2021-05-30 13:00 UTC, Maxim-Bondar commented on src/css/theme/_nav-page.scss
> +    width: 0.5px;
use 1px instead

2021-05-30 13:01 UTC, Maxim-Bondar commented on src/css/theme/_question-list.scss
> +    width: 172px;
don't hardcode

2021-05-30 13:02 UTC, Maxim-Bondar commented on src/css/theme/_question-list.scss
> +    cursor: pointer;
if it is a button you can put this style in common styles

2021-05-30 13:03 UTC, Maxim-Bondar commented on src/css/theme/_question-list.scss
> +    display: none;
Why you need opacity and visibility if you hide an element with display: none?

2021-05-30 13:11 UTC, Maxim-Bondar commented on src/js/burger.js
> +function burgerAnimation (transformFisrtLine, opacitySecondLine, transformThirdLine) {
You don't need this function, create a css class for ex. `is-menu-open` and declare all styles which are needed there and when click the button just add this class to appropriate element. I would also recommend don't use style in js. Create appropriate classes in css and apply it when you need. It is also conserns for `document.querySelector('html').style.overflow = 'hidden';` above

2021-05-30 13:16 UTC, Maxim-Bondar commented on src/js/fixedNavPage.js
> +    const navTips = document.querySelector('#navPage');
id should be in kebab-case, create a new id if you have already such id

2021-05-30 13:18 UTC, Maxim-Bondar commented on src/js/fixedNavPage.js
> +            boxTips.style.height = navTips.offsetHeight + 58 + 'px';
58 is a magic number, create a contant or leave a comment, the same for another numbers here

2021-05-30 13:22 UTC, Maxim-Bondar commented on src/js/checkChoose.js
> +const checkList = document.getElementById('menu-choose').addEventListener('click', e => {
is it for dropdowns? if yes it is a too difficult implementation. You only need it just listen a clik on element by useing `this` and toggle a class `active` if has this class remove if not add

2021-05-30 13:23 UTC, Maxim-Bondar commented on src/js/index.js
> +        if(j === 15 || j === 16 || j === 17 || j === 18 ||j === 19 || j === 20 || j === 21 || j === 22){
what this condition for? what if you will have a 100 elements?

2021-05-30 13:24 UTC, Maxim-Bondar commented on src/js/mainNav.js
> +        console.log(menu.children[i]);
remove console

2021-05-30 13:27 UTC, Maxim-Bondar commented on src/js/navQuestion.js
> +const navQuestion = document.getElementById('questionMenu').addEventListener('click', e => {
why do you need this code if you you have already done a dropdown implementation?

2021-05-30 13:28 UTC, Maxim-Bondar commented on src/templates/footer.html
> +                <h3 class="footer-number">
it is not a title it is a list element

2021-05-30 13:29 UTC, Maxim-Bondar commented on src/templates/footer.html
> +                    <li class="footer-item">Blog</li>
all elements should containe a links inside

2021-05-30 13:31 UTC, Maxim-Bondar commented on src/templates/footer.html
> +                <div class="box-callback">
it is a list instead a div

2021-05-30 13:32 UTC, Maxim-Bondar commented on src/templates/footer.html
> +                    <h3 class="footer-subtitle">
should be a link with appropriate href

2021-05-30 13:33 UTC, Maxim-Bondar commented on src/templates/footer.html
> +            <div class="box-soc">
should be a list with links inside with appropriate urls inside

2021-05-30 13:33 UTC, Maxim-Bondar commented on src/templates/header.html
> +				<div class="burger" id='menu'>
should be a button

2021-05-30 13:34 UTC, Maxim-Bondar commented on src/templates/header.html
> +				<span class='box-logo'>
should be a link

2021-05-30 13:34 UTC, Maxim-Bondar commented on src/templates/header.html
> +						<li class="nav-item"><a class="nav-link">Why Skout</a> </li>
missed href attribute

2021-05-30 13:35 UTC, Maxim-Bondar commented on src/templates/section-slider.html
> +    <div class="box-slider">
it can be an `article`

2021-05-30 13:36 UTC, Maxim-Bondar commented on src/templates/section_tips.html
> +            <div class="box-content animate__animated animate__fadeInLeft ">
use consisten class names in case with `animate__...` this prefix is redundent

2021-05-30 13:38 UTC, Maxim-Bondar commented on src/templates/section_tips.html
> +
use `.prettier` for code formatting it will remove an extra lines etc.

2021-05-30 13:46 UTC, Maxim-Bondar commented on src/templates/section_faqs.html
> +    <button href="#" class="question-link">More question</button>
button don't have a `href` attribute

2021-05-30 13:51 UTC, Maxim-Bondar requested changes
COMMON 
- not centered https://prnt.sc/13ld760
- don't have a hover affect https://prnt.sc/13ld80s re-read a technical task
- arrows is broken https://prnt.sc/13ld9q5  In this case  use icons instead.
- not centered https://prnt.sc/13ldb8u also all area should be clickable
- don't have a hover state https://prnt.sc/13ldgn1
- header is broken and tips section is not fixed https://prnt.sc/13ldhow
- mobile is broken https://prnt.sc/13ldjko https://prnt.sc/13ldkdr
- can open but can't close https://prnt.sc/13ldl74

2021-05-31 12:49 UTC, hellhellpnick commented on src/css/core/_common.scss
> +input {
this is done because all the font on page not standard, but we change it there if necessary

2021-05-31 12:53 UTC, hellhellpnick commented on src/css/core/_vars.scss
> +@function calcRem($size) {
it was not indicated in the assigment that it is necessary to clearly indicate the fonts and how for me to use the rem system is a more universal option

2021-05-31 12:57 UTC, Maxim-Bondar commented on src/css/core/_vars.scss
> +@function calcRem($size) {
All values was mentioned in design, we don't need to describe obvious things if you have strict design

2021-05-31 13:00 UTC, Maxim-Bondar commented on src/css/core/_common.scss
> +input {
ok

2021-05-31 13:00 UTC, hellhellpnick commented on src/css/core/_mixins.scss
> +@mixin padding-hack($padding: 50%, $size: contain, $dev: false) {
I used the word "padding" because the meaning of padding-bottom makes it puzlling what it means. Mixin was created to create a place for a picture :)
I used the word 'dev' because so as not write in full words/sentences. This also takes up a lot of space and you can logically understand that "dev" is for development :)

2021-05-31 13:04 UTC, hellhellpnick commented on src/css/core/_vars.scss
> +$H400: calcRem(110px);
I read the article and I was trained on Bem methodologies. It states the these are time-tested variables

2021-05-31 13:07 UTC, Maxim-Bondar commented on src/css/core/_mixins.scss
> +@mixin padding-hack($padding: 50%, $size: contain, $dev: false) {
Frankly speaking, after your explanation it become more confusing than it was before)) if the mixin needs for picture than call it appropriete and  it is super illogical with argument `development` that change background color

2021-05-31 13:11 UTC, Maxim-Bondar commented on src/css/core/_vars.scss
> +$H400: calcRem(110px);
re-read a comment above, nice to hear that you have an experience with BEM, but question is still open

2021-05-31 13:16 UTC, hellhellpnick commented on src/css/modules/_box.scss
> +  &-logo {
So? why should is use the scss system if this approach is bad? The scss system is nesting and is much more convenient. box { &-logi{}}.

2021-05-31 13:19 UTC, hellhellpnick commented on src/css/modules/_box.scss
> +      flex-direction: row;
if i use the mixin in the media, then all the properties of the mixin will be write again (it turns out with the media i will have 2 flexes), and i need to rewrite 1 property

2021-05-31 13:20 UTC, Maxim-Bondar commented on src/css/modules/_box.scss
> +  &-logo {
Please re-read comment above carefully, I have already described the problem of this approach

2021-05-31 13:21 UTC, hellhellpnick commented on src/css/modules/_burger.scss
> +  &-line:not(:last-child) {
hmm... What if i had a bunch of lines from my elements? Then it would come to rewrite + for this and come up with "not"

2021-05-31 13:24 UTC, Maxim-Bondar commented on src/css/modules/_burger.scss
> +  &-line:not(:last-child) {
Don't understand what do you mean?

2021-05-31 13:27 UTC, hellhellpnick commented on src/css/theme/_nav-choose.scss
> +  border: 1.5px solid $green;
And where did you get the idea that this is a float? I centralized the element in such  a way. Because the top 50% is not the center :/

2021-05-31 13:31 UTC, Maxim-Bondar commented on src/css/theme/_nav-choose.scss
> +  border: 1.5px solid $green;
if number has dot it calls float number 
https://en.wikipedia.org/wiki/Floating-point_arithmetic

2021-05-31 13:53 UTC, hellhellpnick commented on src/css/theme/_question-list.scss
> +    cursor: pointer;
i read the article and there they explained that it was done for cross-browser compatibility

2021-05-31 13:53 UTC, hellhellpnick commented on src/css/theme/_question-list.scss
> +    display: none;
i read the article and there they explained that it was done for cross-browser compatibility

2021-05-31 13:55 UTC, Maxim-Bondar commented on src/css/theme/_question-list.scss
> +    display: none;
please attach a source of this article

2021-05-31 14:17 UTC, hellhellpnick commented on src/css/core/_vars.scss
> +@function calcRem($size) {
Ok

2021-05-31 14:21 UTC, hellhellpnick commented on src/css/core/_mixins.scss
> +@mixin padding-hack($padding: 50%, $size: contain, $dev: false) {
Fixed

2021-05-31 14:21 UTC, hellhellpnick commented on src/css/core/_mixins.scss
> +@mixin size($size) {
Fixed

2021-05-31 14:22 UTC, hellhellpnick commented on src/css/core/_vars.scss
> +$white: white;
Fixed

2021-05-31 14:22 UTC, hellhellpnick commented on src/css/core/_vars.scss
> +$max-width: 1440px;
Fixed

2021-05-31 14:22 UTC, hellhellpnick commented on src/css/core/_vars.scss
> +$screen-iphone-plus: 414px;
Fixed

2021-05-31 14:23 UTC, hellhellpnick commented on src/css/modules/_box.scss
> +    background-color: #f2f2f2;
Fixed

2021-05-31 14:23 UTC, hellhellpnick commented on src/css/theme/_nav-choose.scss
> +    height: 40px;
Fixed

2021-05-31 14:24 UTC, hellhellpnick commented on src/css/theme/_nav-choose.scss
> +    align-items: flex-start;
Fixed

2021-05-31 14:24 UTC, hellhellpnick commented on src/css/theme/_nav-list.scss
> +      @include flex(space-between, center, row);
Fixed

2021-05-31 14:24 UTC, hellhellpnick commented on src/css/theme/_nav-list.scss
> +    content: "";
Fixed

2021-05-31 14:24 UTC, hellhellpnick commented on src/css/theme/_nav-list.scss
> +  &-btn_small {
Fixed

2021-05-31 14:24 UTC, hellhellpnick commented on src/css/theme/_nav-page.scss
> +    width: 0.5px;
Fixed

2021-05-31 14:25 UTC, hellhellpnick commented on src/css/theme/_question-list.scss
> +    cursor: pointer;
Fixed

2021-05-31 14:25 UTC, hellhellpnick commented on src/js/burger.js
> +function burgerAnimation (transformFisrtLine, opacitySecondLine, transformThirdLine) {
Fixed

2021-05-31 14:26 UTC, hellhellpnick commented on src/js/fixedNavPage.js
> +            boxTips.style.height = navTips.offsetHeight + 58 + 'px';
Fixed

2021-05-31 14:26 UTC, hellhellpnick commented on src/js/mainNav.js
> +        console.log(menu.children[i]);
Fixed

2021-05-31 14:26 UTC, hellhellpnick commented on src/templates/footer.html
> +                <h3 class="footer-number">
Fixed

2021-05-31 14:28 UTC, hellhellpnick commented on src/templates/header.html
> +						<li class="nav-item"><a class="nav-link">Why Skout</a> </li>
Fixed

2021-05-31 14:30 UTC, hellhellpnick commented on src/templates/section-slider.html
> +    <div class="box-slider">
This is the name of the classes from the site for animating elements

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"

2021-05-31 14:30 UTC, hellhellpnick commented on src/templates/section_tips.html
> +            <div class="box-content animate__animated animate__fadeInLeft ">
This is the name of the classes from the site for animating elements.

2021-05-31 14:30 UTC, hellhellpnick commented on src/templates/section_tips.html
> +            <div class="box-content animate__animated animate__fadeInLeft ">
<link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"

2021-05-31 14:33 UTC, hellhellpnick commented on src/templates/section_tips.html
> +
Fixed

2021-05-31 14:33 UTC, hellhellpnick commented on src/templates/section_faqs.html
> +    <button href="#" class="question-link">More question</button>
Fixed

2021-05-31 14:46 UTC, Maxim-Bondar commented on src/templates/section_tips.html
> +            <div class="box-content animate__animated animate__fadeInLeft ">
oh, ok

2021-05-31 14:53 UTC, hellhellpnick commented on src/js/navQuestion.js
> +const navQuestion = document.getElementById('questionMenu').addEventListener('click', e => {
During the lesson, you said that list items should be opened by clicking on the list and items list not on the button

2021-05-31 14:55 UTC, hellhellpnick commented on src/js/checkChoose.js
> +const checkList = document.getElementById('menu-choose').addEventListener('click', e => {
During the lesson, you said that list items should be opened by clicking on the list and items list not on the button

2021-05-31 15:00 UTC, Maxim-Bondar commented on src/js/checkChoose.js
> +const checkList = document.getElementById('menu-choose').addEventListener('click', e => {
How it is related to my comment above?

2021-05-31 15:02 UTC, Maxim-Bondar commented on src/js/navQuestion.js
> +const navQuestion = document.getElementById('questionMenu').addEventListener('click', e => {
I mean that you have already had similar functionality, it can be simplify to separate function and used in both cases

2021-06-01 11:54 UTC, hellhellpnick commented on src/css/core/_common.scss
> +}
Fixed

2021-06-01 11:58 UTC, hellhellpnick commented on src/css/modules/_burger.scss
> +  &-line:not(:last-child) {
I changed as you suggested

2021-06-01 11:58 UTC, hellhellpnick commented on src/css/theme/_footer.scss
> +  &-title {
Fixed

2021-06-01 12:01 UTC, hellhellpnick commented on src/css/theme/_footer.scss
> +  &-logo {
Fixed

2021-06-01 12:04 UTC, hellhellpnick commented on src/templates/footer.html
> +                    <li class="footer-item">Blog</li>
Fixed

2021-06-01 12:04 UTC, hellhellpnick commented on src/templates/footer.html
> +                <div class="box-callback">
Fixed

2021-06-01 12:06 UTC, hellhellpnick commented on src/templates/footer.html
> +                    <h3 class="footer-subtitle">
Fixed

2021-06-01 12:07 UTC, hellhellpnick commented on src/templates/section-slider.html
> +    <div class="box-slider">
Fixed

2021-06-01 12:16 UTC, hellhellpnick commented on src/css/core/_vars.scss
> +$H400: calcRem(110px);
What is the best way for me to name the variables? `fontSize12`

2021-06-01 12:18 UTC, hellhellpnick commented on src/css/modules/_box.scss
> +  &-logo {
That is, I shouldn't use nesting? And write everything in full names? Example, `.box-logo{}`

2021-06-01 12:34 UTC, hellhellpnick commented on src/js/fixedNavPage.js
> +    const navTips = document.querySelector('#navPage');
if I understood correctly, then I corrected

2021-06-01 13:06 UTC, Maxim-Bondar commented on src/css/modules/_box.scss
> +      flex-direction: row;
ok

2021-06-01 13:08 UTC, Maxim-Bondar commented on src/css/modules/_box.scss
> +  &-logo {
no, you don't even extend a perent class name , you can just use `.logo`, anyway the styles apply in `.box` section

2021-06-01 13:10 UTC, Maxim-Bondar commented on src/css/core/_vars.scss
> +$H400: calcRem(110px);
I would recommend such names as `fontSizeSmall, fontSizeMedium, fontSizeLarge`

2021-06-01 13:20 UTC, hellhellpnick commented on src/css/core/_vars.scss
> +$H400: calcRem(110px);
In my opinion, this is not practical, only in this task there are already 6 font sizes. If I call the same plan, `fontSizeSmall / fontSizeSecondSmall`. I will at least add more possibilities in the name

2021-06-01 13:24 UTC, Maxim-Bondar commented on src/css/core/_vars.scss
> +$H400: calcRem(110px);
Who told you name variable as `fontSizeSecondSmall` ?  if application has more than 6 fon't sizes it is a mess

2021-06-01 13:27 UTC, Maxim-Bondar commented on src/css/core/_vars.scss
> +$H400: calcRem(110px);
You are going to work with people not with machines, your code should be simple and understandable

2021-06-01 13:29 UTC, hellhellpnick commented on src/css/core/_vars.scss
> +$H400: calcRem(110px);
Nobody told me the name of the variable `fontSizeSecondSmall` I assumed. So the layout uses defferent font sizes 12, 14, 16, 24, 32 and 110. How should I call them in this situation?

2021-06-01 14:41 UTC, hellhellpnick commented on src/css/modules/_box.scss
> +  &-logo {
if I understood correctly, then I corrected

2021-06-01 14:42 UTC, hellhellpnick commented on src/templates/footer.html
> +            <div class="box-soc">
Fixed

2021-06-01 14:43 UTC, hellhellpnick commented on src/templates/header.html
> +				<div class="burger" id='menu'>
Fixed

2021-06-01 14:43 UTC, hellhellpnick commented on src/templates/header.html
> +				<span class='box-logo'>
Fixed

2021-06-01 17:02 UTC, hellhellpnick commented on src/css/theme/_nav-choose.scss
> +      font-weight: 300;
Fixed

2021-06-01 17:04 UTC, hellhellpnick commented on src/css/theme/_nav-choose.scss
> +  border: 1.5px solid $green;
Fixed

2021-06-01 17:06 UTC, hellhellpnick commented on src/css/theme/_question-list.scss
> +    display: none;
I haven't found this article. Therefore, I will change to `display: none`

2021-06-02 11:42 UTC, hellhellpnick commented on src/css/theme/_nav-choose.scss
> +      font-weight: 300;
Fixed

2021-06-02 11:42 UTC, hellhellpnick commented on src/css/theme/_nav-choose.scss
> +  border: 1.5px solid $green;
Fixed

2021-06-02 12:07 UTC, hellhellpnick commented on src/js/index.js
> +        if(j === 15 || j === 16 || j === 17 || j === 18 ||j === 19 || j === 20 || j === 21 || j === 22){
what should I do if I don't how to do it normally?

2021-06-02 12:20 UTC, Maxim-Bondar commented on src/js/index.js
> +        if(j === 15 || j === 16 || j === 17 || j === 18 ||j === 19 || j === 20 || j === 21 || j === 22){
leave it as it is for now, the main accent of this task is markup

2021-06-02 12:23 UTC, hellhellpnick commented on src/js/index.js
> +        if(j === 15 || j === 16 || j === 17 || j === 18 ||j === 19 || j === 20 || j === 21 || j === 22){
Ok

2021-06-02 14:29 UTC, hellhellpnick commented on src/js/navQuestion.js
> +const navQuestion = document.getElementById('questionMenu').addEventListener('click', e => {
I redid it through forEach, but now it will not remove classes from others if one is open and you open another
```
const checkList = function(){
	let items = [...document.querySelectorAll('.menu-item')];
	const menu = document.getElementById('menu-choose');

	items.forEach(main =>{
		let btn = main.querySelector('.check');

		btn.addEventListener('click', () => {
			main.classList.toggle('check-active')
		});
	})
};

export default checkList;
```

2021-06-02 14:32 UTC, hellhellpnick commented on .gitignore
> +node_modules/
The file will appear when I fill this task))
I can't push straight there

2021-06-11 09:27 UTC, Maxim-Bondar commented on src/css/core/_vars.scss
> +$max-width: 1440px;
not fixed

2021-06-11 13:28 UTC, Maxim-Bondar commented on src/css/core/_vars.scss
> +@function calcRem($size) {
not fixed

2021-06-11 13:29 UTC, Maxim-Bondar commented on src/css/core/_mixins.scss
> +  $development: false
we have already disscussed about this argument, why you have left it here ?

2021-06-11 13:29 UTC, Maxim-Bondar commented on src/css/core/_mixins.scss
> +    @if $dev {
undefined variable

2021-06-11 13:31 UTC, Maxim-Bondar commented on src/css/core/_vars.scss
> +$white-color: #fff;
not fixed. We have already disscused it 
previous comment `bad idea make variables with strict dependency to the value, imagene situation when you will change the value to another collor but the variable will have the white name, Was discussed on the last meeting`

2021-06-11 13:31 UTC, Maxim-Bondar commented on src/css/core/_vars.scss
> +$H400: 110px;
not fixed

2021-06-11 13:32 UTC, Maxim-Bondar commented on src/css/core/_vars.scss
> +$screen-iphone: 375px;
not fixed, was in previous review

2021-06-11 13:33 UTC, Maxim-Bondar commented on src/css/layout/_header.scss
> +  padding: 20px 18px 40px 18px;
can be simplify to `20 18 40`

2021-06-11 13:35 UTC, Maxim-Bondar commented on src/css/modules/_box.scss
> +    padding-left: 20px;
redundent padding, us only one key for style declaration

2021-06-11 13:37 UTC, Maxim-Bondar commented on src/css/modules/_burger.scss
> +    display: none;
Why you use all this styles here?

2021-06-11 13:38 UTC, Maxim-Bondar commented on src/css/modules/_wrapper.scss
> +      margin: 0;
use shorthand for margin

2021-06-11 13:38 UTC, Maxim-Bondar commented on src/css/modules/_wrapper.scss
> +      width: 80%;
magic number

2021-06-11 13:41 UTC, Maxim-Bondar commented on src/css/theme/_footer.scss
> +    @include text($H100, 400, $grey-color);
this styles also must be in common class as for title because it the same as for title

2021-06-11 13:43 UTC, Maxim-Bondar commented on src/css/theme/_nav-choose.scss
> +    padding: 17px 0 12px 0;
`17 0 12`

2021-06-11 13:47 UTC, Maxim-Bondar commented on src/css/theme/_nav-choose.scss
> +      left: 23%;
magic number

2021-06-11 13:47 UTC, Maxim-Bondar commented on src/css/theme/_nav-choose.scss
> +      top: 47%;
magic number

2021-06-11 13:48 UTC, Maxim-Bondar commented on src/css/theme/_nav-choose.scss
> +    .menu-text {
use helper class instead for such purpose

2021-06-11 13:49 UTC, Maxim-Bondar commented on src/css/theme/_nav-choose.scss
> +    & > p {
use class instead

2021-06-11 13:49 UTC, Maxim-Bondar commented on src/css/theme/_nav-list.scss
> +    list-style: none;
not fixed

2021-06-11 13:52 UTC, Maxim-Bondar commented on src/css/theme/_nav-list.scss
> +      margin-bottom: 0;
u have already declared this style above

2021-06-11 13:53 UTC, Maxim-Bondar commented on src/css/theme/_nav-list.scss
> +    cursor: pointer;
redundent style, was declare in common styles

2021-06-11 13:54 UTC, Maxim-Bondar commented on src/css/theme/_nav-list.scss
> +    padding: 8px 52px;
paddings must be the same for all buttons

2021-06-11 13:55 UTC, Maxim-Bondar commented on src/css/theme/_nav-list.scss
> +      margin-right: 20px;
it is not correct, indents must be on the parent not the child

2021-06-11 13:56 UTC, Maxim-Bondar commented on src/css/theme/_nav-list.scss
> +    @include flex(flex-end, center, row);
why class `invisible` make changes in container layout by flex?

2021-06-11 13:56 UTC, Maxim-Bondar commented on src/css/theme/_nav-list.scss
> +.visible {
the same as above

2021-06-11 13:57 UTC, Maxim-Bondar commented on src/css/theme/_nav-list.scss
> +  font-family: $logo-font;
variable was created for logo but u use it for title

2021-06-11 13:58 UTC, Maxim-Bondar commented on src/css/theme/_nav-list.scss
> +  max-width: 142px;
redundent style

2021-06-11 13:58 UTC, Maxim-Bondar commented on src/css/theme/_nav-list.scss
> +    max-width: 1100px;
the same as above

2021-06-11 13:58 UTC, Maxim-Bondar commented on src/css/theme/_nav-list.scss
> +    padding-top: 24px;
why you add this padding?

2021-06-11 13:59 UTC, Maxim-Bondar commented on src/css/theme/_nav-page.scss
> +  margin-top: -20px;
use only one declarations/ you hae already declare margin above

2021-06-11 13:59 UTC, Maxim-Bondar commented on src/css/theme/_nav-page.scss
> +  padding: 11px 0px 13px 0px;
use shorthand

2021-06-11 13:59 UTC, Maxim-Bondar commented on src/css/theme/_nav-page.scss
> +    padding: 11px 33px 13px 33px;
the same as above

2021-06-11 14:01 UTC, Maxim-Bondar commented on src/css/theme/_nav-page.scss
> +  &:not(:last-child)::after {
have already disscussed such selector use use selector with operator `+` instead

2021-06-11 14:05 UTC, Maxim-Bondar commented on src/css/theme/_question-list.scss
> +    cursor: pointer;
redundent style

2021-06-11 14:05 UTC, Maxim-Bondar commented on src/css/theme/_question-list.scss
> +    outline: none;
those style also was declared in common styles

2021-06-11 14:06 UTC, Maxim-Bondar commented on src/css/theme/_question-list.scss
> +  &-visible {
how word `visible` is conected to styles below?

2021-06-11 14:10 UTC, Maxim-Bondar commented on src/templates/footer.html
> +          <li class="footer-item "><a href="#" class="footer-link footer-number">1-855-838-4500</a></li>
href must contain `tel:`

2021-06-11 14:10 UTC, Maxim-Bondar commented on src/templates/footer.html
> +          <p class="footer-text">
tag `address`

2021-06-11 14:10 UTC, Maxim-Bondar commented on src/templates/footer.html
> +          <h2 class="footer-title footer-subtitle">+1 631-203-6600</h2>
link with appropriate href attribute

2021-06-11 14:11 UTC, Maxim-Bondar commented on src/templates/footer.html
> +        <a class="footer-img_link" href="https://www.twitch.tv/s"><img class="footer-img" src="../images/twitch.png" />
missed closing tag

2021-06-11 14:11 UTC, Maxim-Bondar commented on src/templates/footer.html
> +        <button class="footer-logo">Skout</button>
logo must be a link

2021-06-11 14:11 UTC, Maxim-Bondar commented on src/templates/header.html
> +				<div class="burger" id='menu'>
not fixed

2021-06-11 14:12 UTC, Maxim-Bondar commented on src/templates/header.html
> +				<a class='logo'>
missed href

2021-06-11 14:12 UTC, Maxim-Bondar commented on src/templates/section-slider.html
> +    <div class="arrow-next">
must be a button

2021-06-11 14:13 UTC, Maxim-Bondar commented on src/templates/section_faqs.html
> +  <ul class="question-list" id="questionMenu">
id as class name should be in kebab-case

2021-06-11 14:15 UTC, Maxim-Bondar commented on src/templates/section_faqs.html
> +      <button class="question-arrow"></button>
shouldn't be arrow here

2021-06-11 14:16 UTC, Maxim-Bondar commented on src/templates/section_faqs.html
> +      <article class="box-question">
it is not an article, it should be a button and all area must be clickable

2021-06-11 14:17 UTC, Maxim-Bondar commented on src/templates/section_tips.html
> +      <span class="menu-text">1</span>
wrapper must be a button and all area should be clickable except dropdown body

2021-06-11 14:18 UTC, Maxim-Bondar commented on src/templates/section_tips.html
> +
you don't have prettier settings

2021-06-11 14:25 UTC, Maxim-Bondar requested changes
COOMMON 
- remove all magic numbers for ex 47%, 13% etc.
- use shorthand for margin and padding 
- header is broken and tips section is not fixed https://prnt.sc/13ldhow
- arrows is broken https://prnt.sc/13ld9q5 In this case use icons instead.
- tablet is broken http://i.prntscr.com/tgpw_qGiQy6YsBKhMbQiNg.png

2021-06-17 12:44 UTC, Maxim-Bondar approved these changes

2021-06-17 12:44 UTC, merged