done ts_3
hellhellpnick/Vodoriz_Alexander_AltexsoftLab pull request #7
Opened 2021-07-06 10:53 UTC by hellhellpnick

2021-07-08 09:47 UTC, marynakorol requested changes

2021-07-08 09:47 UTC, marynakorol commented on homework_3/src/js/dominoes.js
> +      const listTwo = dominoesListTwo.filter((item) => item == i)
better to use strong comparing (===) if you are sure you have equal types

2021-07-08 09:47 UTC, marynakorol commented on homework_3/src/js/dominoes.js
> +export default function dominoes() {
rename please your function with the verb to understand what it might do and try to isolate some 'for' conditions to new functions to avoid repeating (according SOLID )

2021-07-08 09:47 UTC, marynakorol commented on homework_3/src/js/dominoes.js
> +    if (listOneMaxCount[1] >= listTwoMaxCount[1]) {
think about how you can avoid repeating here

2021-07-08 09:47 UTC, marynakorol commented on homework_3/src/js/dominoes.js
> +      dominoesText.innerHTML = '2'
the result must show a number of rotations to get one string with the same values. You have a hardcoded value here, so the result is wrong 
![image](https://user-images.githubusercontent.com/84564899/124897734-413eb480-dfe7-11eb-8317-eff3da74dedc.png)
must be 0 here, cause you have all "2" at the top

2021-07-08 09:47 UTC, marynakorol commented on homework_3/src/js/dominoes.js
> +      dominoesText.innerHTML = '2'
the logic doesn't work correctly, look, this can't be success result 
![image](https://user-images.githubusercontent.com/84564899/124899297-a5ae4380-dfe8-11eb-84a8-e2f71640e503.png)
and you have success after the sort is clicked, that is strange 
![image](https://user-images.githubusercontent.com/84564899/124899387-bc549a80-dfe8-11eb-8099-d51163ef50ec.png)

2021-07-08 09:47 UTC, marynakorol commented on homework_3/src/js/dominoes.js
> +      dominoesText.innerHTML = '2'
all dominoes have other values after sorting

2021-07-08 09:47 UTC, marynakorol commented on homework_3/src/js/stairs.js
> +  stairs.addEventListener('change', (e) => {
input must get only numbers and  return the result - the number of full rows 
![image](https://user-images.githubusercontent.com/84564899/124901330-94663680-dfea-11eb-8e17-4f7dc8cff8c0.png)

2021-07-13 12:22 UTC, hellhellpnick commented on homework_3/src/index.html
> +      <ul id="dominoes-one" class="domino"></ul>
Fixed

2021-07-13 12:31 UTC, hellhellpnick commented on homework_3/src/js/cashMachine.js
> +let iWantToGet = (ammountRequired, limits, finalLimits) => {
Renamed on iWantToGetCashFromMachine

2021-07-13 12:34 UTC, hellhellpnick commented on homework_3/src/js/cashMachine.js
> +    if (amount === 0) return {}
Fixed

2021-07-13 13:28 UTC, hellhellpnick commented on homework_3/src/js/cashMachine.js
> +      currencyError.innerHTML = 'The number is not a string'
Added reg for input

2021-07-13 13:28 UTC, hellhellpnick commented on homework_3/src/js/cashMachine.js
> +
Added conditional

2021-07-13 13:28 UTC, hellhellpnick commented on homework_3/src/js/cashMachine.js
> +    takeOff = document.getElementById('take-off')
Changed file 'prettier'

2021-07-13 13:28 UTC, hellhellpnick commented on homework_3/src/js/cashMachine.js
> +      let result = collect(amount - i * currentNominal, nominals.slice(1))
Fixed

2021-07-13 13:29 UTC, hellhellpnick commented on homework_3/src/js/cashMachine.js
> +    let numberOfNotes = Math.min(availableNotes, notesNeeded)
Fixed

2021-07-13 14:09 UTC, hellhellpnick commented on homework_3/src/js/stairs.js
> +  stairs.addEventListener('change', (e) => {
Fixed

2021-07-13 14:19 UTC, hellhellpnick commented on homework_3/src/js/dominoes.js
> +      const listTwo = dominoesListTwo.filter((item) => item == i)
Fixed

2021-07-15 09:27 UTC, hellhellpnick commented on homework_3/src/js/dominoes.js
> +    if (listOneMaxCount[1] >= listTwoMaxCount[1]) {
I have no ideas

2021-07-15 09:27 UTC, hellhellpnick commented on homework_3/src/js/dominoes.js
> +      dominoesText.innerHTML = '2'
Fixed

2021-07-19 11:16 UTC, marynakorol commented on homework_3/src/js/cashMachine.js
> +    if (amount === 0) return {}
it needed to return an object or an array to work. you can define them or restructure a function to return results clearer

2021-07-19 11:18 UTC, marynakorol commented on homework_3/README.md
> +<p align="center">
👍 like from for the Readme file with instructions. it's a good practice for future projects.

2021-07-19 11:19 UTC, marynakorol approved these changes

2021-07-19 11:19 UTC, merged