done ts_4
hellhellpnick/Vodoriz_Alexander_AltexsoftLab pull request #8
Opened 2021-07-16 13:22 UTC by hellhellpnick

2021-07-19 21:05 UTC, Korew requested changes
Please create functionality for adding/removing data from db.json

Separate input for ID field not needed - all id's should be created in background. 

When I click on delete button, I assume row will be deleted (will be good if you create confirmation popup to avoid accidental deletion).

For mass actions (when you select several checkboxes) - you need another button.

Please read comments and fix them all over the project (not only where I added comment)

If you repeat code twice (or more) - please create function for it.

2021-07-20 09:09 UTC, hellhellpnick commented on homework_4/css/form-add.css
> +.form-add-btn {
Fixed

2021-07-20 09:39 UTC, hellhellpnick commented on homework_4/css/form-add.css
> +  outline: none;
Fixed

2021-07-20 09:39 UTC, hellhellpnick commented on homework_4/css/inherit.css
> +}
Fixed

2021-07-20 09:39 UTC, hellhellpnick commented on homework_4/js/main.js
> +  let box = document.createElement('div');
Fixed

2021-07-20 09:41 UTC, hellhellpnick commented on homework_4/js/main.js
> +const workWithElemnt = function workWithElemntToMainTable(id) {
Fixed

2021-07-20 09:41 UTC, hellhellpnick commented on homework_4/js/main.js
> +  btnClose.setAttribute('type', 'submit');
Fixed

2021-07-20 09:43 UTC, hellhellpnick commented on homework_4/js/main.js
> +  form.addEventListener('submit', (e) => {
I know, but it's making my `prettier`

2021-07-20 09:50 UTC, hellhellpnick commented on homework_4/js/main.js
> +const workWithElemnt = function workWithElemntToMainTable(id) {
When I was at work, I was advised to use the entire function declaration. First, it is called a short name for use, and if you do not understand what this function does (by the short name), then you look at the full name

2021-07-20 09:50 UTC, hellhellpnick commented on homework_4/js/main.js
> +const workWithElemnt = function workWithElemntToMainTable(id) {
and in any case, you are called through a short name

2021-07-20 09:52 UTC, hellhellpnick commented on homework_4/js/main.js
> +      if (id == elem.id) {
Fixed

2021-07-20 09:54 UTC, hellhellpnick commented on homework_4/js/main.js
> +  let inputId = document.createElement('input');
Okay. I'm understand what do you mean, but how should I get id from new elements when I create?

2021-07-20 10:29 UTC, hellhellpnick commented on homework_4/js/main.js
> +  inputId.classList.add('form-add-input');
Fixed

2021-07-22 13:52 UTC, Korew requested changes

2021-07-22 13:52 UTC, Korew commented on homework_4/js/main.js
> +  form.addEventListener('submit', (e) => {
ok, not a problem

2021-07-22 13:52 UTC, Korew commented on homework_4/js/main.js
> +const createRandomSymbols = function createRandomCountSymbols(length) {
please fix

2021-07-22 13:52 UTC, Korew commented on homework_4/js/main.js
> +  const inputId = document.createElement('input');
remove input for id

2021-07-23 23:10 UTC, Korew approved these changes

2021-07-23 23:10 UTC, merged